In [4]:
#Q1
import numpy as np
def weird_matrix(a,b,increasing=False):
    if increasing:
        op=np.array([x**i for x in a for i in range(b)]).reshape(a.size,b)
    elif not increasing:
        op= np.array([x**(n-1-i) for x in a for i in range(b)]).reshape(a.size,b)
    
    return op
    
ip=np.array([1,2,3,4,5])
n=3
dec=weird_matrix(ip,n,increasing=False)
inc=weird_matrix(ip,n,increasing=True)
inc 


array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

In [5]:
dec

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [8]:
#q2
def mvng_avg(a,n=3):
    asum=np.cumsum(a,dtype=float)
    asum[n:]=asum[n:]-asum[:-n]
    return asum[n-1:]/n
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
np.array(mvng_avg(a,n=3))

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])